-- 献立アプリの必須となるテーブルを作成するためのDDL
-- 環境はPostgreSQL

-- 共通システム列は下記の通り
-- VERSION: 楽観的排他制御のためのバージョン番号
-- CREATED_AT: レコード作成日時
-- CREATED_BY: レコード作成者
-- UPDATED_AT: レコード更新日時
-- UPDATED_BY: レコード更新者


-- 献立
CREATE SEQUENCE KONDATE_SEQ START WITH 1 INCREMENT BY 1;

CREATE TABLE KONDATE (
    KONDATE_ID KONDATE_SEQ PRIMARY KEY DEFAULT nextval('KONDATE_SEQ'),
    -- YYYY-MM-DD 形式で保存
    KONDATE_DATE DATE NOT NULL,
    TITLE VARCHAR(100) NOT NULL,
    DESCRIPTION VARCHAR(100),
    VERSION INTEGER DEFAULT 1,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY VARCHAR(50),
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY VARCHAR(50)
    );

COMMENT ON TABLE KONDATE IS '献立';

COMMENT ON COLUMN KONDATE.KONDATE_ID IS '献立ID';
COMMENT ON COLUMN KONDATE.KONDATE_DATE IS '献立日付';
COMMENT ON COLUMN KONDATE.TITLE IS '献立名';
COMMENT ON COLUMN KONDATE.DESCRIPTION IS '献立説明';
COMMENT ON COLUMN KONDATE.VERSION IS 'バージョン';
COMMENT ON COLUMN KONDATE.CREATED_AT IS '作成日時';
COMMENT ON COLUMN KONDATE.CREATED_BY IS '作成者';
COMMENT ON COLUMN KONDATE.UPDATED_AT IS '更新日時';
COMMENT ON COLUMN KONDATE.UPDATED_BY IS '更新者';

-- レシピテーブル
-- 献立テーブルと1対多の関係

CREATE SEQUENCE RECIPE_SEQ START WITH 1 INCREMENT BY 1;

CREATE TABLE RECIPE (
    RECIPE_ID RECIPE_SEQ PRIMARY KEY DEFAULT nextval('RECIPE_SEQ'),
    KONDATE_ID INTEGER NOT NULL,
    RECIPE_NAME VARCHAR(100) NOT NULL,
    INSTRUCTIONS VARCHAR(10000),
    VERSION INTEGER DEFAULT 1,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY VARCHAR(50),
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY VARCHAR(50),
    FOREIGN KEY (KONDATE_ID) REFERENCES KONDATE(KONDATE_ID)
    );


COMMENT ON TABLE RECIPE IS 'レシピ';

COMMENT ON COLUMN RECIPE.RECIPE_ID IS 'レシピID';
COMMENT ON COLUMN RECIPE.KONDATE_ID IS '献立ID';
COMMENT ON COLUMN RECIPE.RECIPE_NAME IS 'レシピ名';
COMMENT ON COLUMN RECIPE.INSTRUCTIONS IS '調理手順';
COMMENT ON COLUMN RECIPE.VERSION IS 'バージョン';
COMMENT ON COLUMN RECIPE.CREATED_AT IS '作成日時';
COMMENT ON COLUMN RECIPE.CREATED_BY IS '作成者';
COMMENT ON COLUMN RECIPE.UPDATED_AT IS '更新日時';
COMMENT ON COLUMN RECIPE.UPDATED_BY IS '更新者';

-- レシピ材料
-- レシピテーブルと1対多の関係
-- 材料テーブルと多対1の関係
-- これは、レシピテーブルと材料テーブルの多対多の関係を解決するための中間テーブルです。

CREATE TABLE RECIPE_INGREDIENT (
    RECIPE_ID INTEGER NOT NULL,
    INGREDIENT_ID INTEGER NOT NULL,
    AMOUNT_NUMERIC NUMERIC NOT NULL,
    UNIT_ID INTEGER NOT NULL,
    VERSION INTEGER DEFAULT 1,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY VARCHAR(50),
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY VARCHAR(50),
    PRIMARY KEY (RECIPE_ID, INGREDIENT_ID),
    FOREIGN KEY (RECIPE_ID) REFERENCES RECIPE(RECIPE_ID),
    FOREIGN KEY (INGREDIENT_ID) REFERENCES INGREDIENT(INGREDIENT_ID),
    FOREIGN KEY (UNIT_ID) REFERENCES UNIT(UNIT_ID)
);

COMMENT ON TABLE RECIPE_INGREDIENT IS 'レシピ材料';

COMMENT ON COLUMN RECIPE_INGREDIENT.RECIPE_ID IS 'レシピID';
COMMENT ON COLUMN RECIPE_INGREDIENT.INGREDIENT_ID IS '材料ID';
COMMENT ON COLUMN RECIPE_INGREDIENT.AMOUNT_NUMERIC IS '完全な数量（g/ml/個などで統一）';
COMMENT ON COLUMN RECIPE_INGREDIENT.VERSION IS 'バージョン';
COMMENT ON COLUMN RECIPE_INGREDIENT.CREATED_AT IS '作成日時';
COMMENT ON COLUMN RECIPE_INGREDIENT.CREATED_BY IS '作成者';
COMMENT ON COLUMN RECIPE_INGREDIENT.UPDATED_AT IS '更新日時';
COMMENT ON COLUMN RECIPE_INGREDIENT.UPDATED_BY IS '更新者';

-- 材料テーブル
-- レシピ材料テーブルと1対多の関係
CREATE SEQUENCE INGREDIENT_SEQ START WITH 1 INCREMENT BY 1;
CREATE TABLE INGREDIENT (
    INGREDIENT_ID INGREDIENT_SEQ PRIMARY KEY DEFAULT nextval('INGREDIENT_SEQ'),
    INGREDIENT_NAME VARCHAR(100) NOT NULL,
    DESCRIPTION VARCHAR(255),
    VERSION INTEGER DEFAULT 1,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY VARCHAR(50),
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY VARCHAR(50)
    );

COMMENT ON TABLE INGREDIENT IS '材料';

COMMENT ON COLUMN INGREDIENT.INGREDIENT_ID IS '材料ID';
COMMENT ON COLUMN INGREDIENT.INGREDIENT_NAME IS '材料名';
COMMENT ON COLUMN INGREDIENT.DESCRIPTION IS '材料説明';
COMMENT ON COLUMN INGREDIENT.VERSION IS 'バージョン';
COMMENT ON COLUMN INGREDIENT.CREATED_AT IS '作成日時';
COMMENT ON COLUMN INGREDIENT.CREATED_BY IS '作成者';
COMMENT ON COLUMN INGREDIENT.UPDATED_AT IS '更新日時';
COMMENT ON COLUMN INGREDIENT.UPDATED_BY IS '更新者';

-- ストックテーブル
-- 材料テーブルと多対1の関係
CREATE SEQUENCE STOCK_SEQ START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE STOCK_SEQ START WITH 1 INCREMENT BY 1;

CREATE TABLE STOCK (
    STOCK_ID INTEGER PRIMARY KEY DEFAULT nextval('STOCK_SEQ'),
    INGREDIENT_ID INTEGER NOT NULL,
    AMOUNT_NUMERIC NUMERIC NOT NULL,
    UNIT_ID INTEGER NOT NULL,
    VERSION INTEGER DEFAULT 1,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY VARCHAR(50),
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY VARCHAR(50),
    FOREIGN KEY (INGREDIENT_ID) REFERENCES INGREDIENT(INGREDIENT_ID),
    FOREIGN KEY (UNIT_ID) REFERENCES UNIT(UNIT_ID)
);


COMMENT ON TABLE STOCK IS 'ストック';
COMMENT ON COLUMN STOCK.STOCK_ID IS 'ストックID';
COMMENT ON COLUMN STOCK.INGREDIENT_ID IS '材料ID';
COMMENT ON COLUMN STOCK.AMOUNT IS '数量';
COMMENT ON COLUMN STOCK.QUANTITY IS '単位';
COMMENT ON COLUMN STOCK.VERSION IS 'バージョン';
COMMENT ON COLUMN STOCK.CREATED_AT IS '作成日時';
COMMENT ON COLUMN STOCK.CREATED_BY IS '作成者';
COMMENT ON COLUMN STOCK.UPDATED_AT IS '更新日時';
COMMENT ON COLUMN STOCK.UPDATED_BY IS '更新者';


-- 標準単位マスタテーブル

CREATE SEQUENCE UNIT_SEQ START WITH 1 INCREMENT BY 1;

CREATE TABLE UNIT (
    UNIT_ID INTEGER PRIMARY KEY DEFAULT nextval('UNIT_SEQ'),
    UNIT_NAME VARCHAR(50) NOT NULL,     -- g, ml, 個, 本, 枚 など
    VERSION INTEGER DEFAULT 1,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY VARCHAR(50),
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY VARCHAR(50)
);

COMMENT ON TABLE UNIT IS '標準単位マスタ（g, ml, 個など）';
COMMENT ON COLUMN UNIT.UNIT_ID IS '単位ID';
COMMENT ON COLUMN UNIT.UNIT_NAME IS '単位名';
COMMENT ON COLUMN UNIT.VERSION IS 'バージョン';
COMMENT ON COLUMN UNIT.CREATED_AT IS '作成日時';
COMMENT ON COLUMN UNIT.CREATED_BY IS '作成者';
COMMENT ON COLUMN UNIT.UPDATED_AT IS '更新日時';
COMMENT ON COLUMN UNIT.UPDATED_BY IS '更新者';
