-- テストデータを入れるDDL

-- 単位マスタのテストデータ
INSERT INTO UNIT (UNIT_NAME, CREATED_BY, UPDATED_BY) VALUES ('g', 'system', 'system');
INSERT INTO UNIT (UNIT_NAME, CREATED_BY, UPDATED_BY) VALUES ('ml', 'system', 'system');
INSERT INTO UNIT (UNIT_NAME, CREATED_BY, UPDATED_BY) VALUES ('個', 'system', 'system');
INSERT INTO UNIT (UNIT_NAME, CREATED_BY, UPDATED_BY) VALUES ('本', 'system', 'system');
INSERT INTO UNIT (UNIT_NAME, CREATED_BY, UPDATED_BY) VALUES ('枚', 'system', 'system');

-- 材料のテストデータ
INSERT INTO INGREDIENT (INGREDIENT_NAME, DESCRIPTION, CREATED_BY, UPDATED_BY) VALUES ('鶏肉', '鶏むね肉', 'system', 'system');
INSERT INTO INGREDIENT (INGREDIENT_NAME, DESCRIPTION, CREATED_BY, UPDATED_BY) VALUES ('塩', '食塩', 'system', 'system');
INSERT INTO INGREDIENT (INGREDIENT_NAME, DESCRIPTION, CREATED_BY, UPDATED_BY) VALUES ('醤油', '濃口醤油', 'system', 'system');
INSERT INTO INGREDIENT (INGREDIENT_NAME, DESCRIPTION, CREATED_BY, UPDATED_BY) VALUES ('玉ねぎ', '中玉ねぎ', 'system', 'system');
INSERT INTO INGREDIENT (INGREDIENT_NAME, DESCRIPTION, CREATED_BY, UPDATED_BY) VALUES ('ニンニク', 'みじん切り', 'system', 'system');

-- 献立のテストデータ
INSERT INTO KONDATE (KONDATE_DATE, TITLE, DESCRIPTION, CREATED_BY, UPDATED_BY) VALUES ('2024-01-15', '鶏肉の塩焼き定食', 'シンプルで美味しい定食', 'system', 'system');
INSERT INTO KONDATE (KONDATE_DATE, TITLE, DESCRIPTION, CREATED_BY, UPDATED_BY) VALUES ('2024-01-16', 'チキンステーキ', 'にんにく香る鶏肉料理', 'system', 'system');

-- レシピのテストデータ
INSERT INTO RECIPE (KONDATE_ID, RECIPE_NAME, INSTRUCTIONS, CREATED_BY, UPDATED_BY) VALUES (1, '鶏肉の塩焼き', '1.鶏肉に塩を振る 2.フライパンで焼く 3.完成', 'system', 'system');
INSERT INTO RECIPE (KONDATE_ID, RECIPE_NAME, INSTRUCTIONS, CREATED_BY, UPDATED_BY) VALUES (2, 'チキンステーキ', '1.ニンニクをみじん切りにする 2.鶏肉にニンニクを擦り込む 3.醤油で焼く', 'system', 'system');

-- レシピ材料のテストデータ
INSERT INTO RECIPE_INGREDIENT (RECIPE_ID, INGREDIENT_ID, AMOUNT_NUMERIC, UNIT_ID) VALUES (1, 1, 300, 1);
INSERT INTO RECIPE_INGREDIENT (RECIPE_ID, INGREDIENT_ID, AMOUNT_NUMERIC, UNIT_ID) VALUES (1, 2, 5, 1);
INSERT INTO RECIPE_INGREDIENT (RECIPE_ID, INGREDIENT_ID, AMOUNT_NUMERIC, UNIT_ID) VALUES (2, 1, 400, 1);
INSERT INTO RECIPE_INGREDIENT (RECIPE_ID, INGREDIENT_ID, AMOUNT_NUMERIC, UNIT_ID) VALUES (2, 5, 10, 1);
INSERT INTO RECIPE_INGREDIENT (RECIPE_ID, INGREDIENT_ID, AMOUNT_NUMERIC, UNIT_ID) VALUES (2, 3, 30, 2);

-- ストックのテストデータ
INSERT INTO STOCK (INGREDIENT_ID, AMOUNT_NUMERIC, UNIT_ID, CREATED_BY, UPDATED_BY) VALUES (1, 500, 1, 'system', 'system');
INSERT INTO STOCK (INGREDIENT_ID, AMOUNT_NUMERIC, UNIT_ID, CREATED_BY, UPDATED_BY) VALUES (2, 100, 1, 'system', 'system');
INSERT INTO STOCK (INGREDIENT_ID, AMOUNT_NUMERIC, UNIT_ID, CREATED_BY, UPDATED_BY) VALUES (3, 500, 2, 'system', 'system');
INSERT INTO STOCK (INGREDIENT_ID, AMOUNT_NUMERIC, UNIT_ID, CREATED_BY, UPDATED_BY) VALUES (4, 5, 3, 'system', 'system');
INSERT INTO STOCK (INGREDIENT_ID, AMOUNT_NUMERIC, UNIT_ID, CREATED_BY, UPDATED_BY) VALUES (5, 50, 1, 'system', 'system');